### ISSUE TITLE
D4  generalizing definitions of roles

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#101]
Various classes and properties in the ontology referring to author/contributor roles have definitions specific to NCA3.  Given that many non-NCA3 documents are cited or will be traced in the GCIS, we prefer generalizing those definitions.

i.e.: http://data.globalchange.gov/gcis.owl#ReviewEditor
      http://data.globalchange.gov/gcis.owl#ContributingAuthor
      http://data.globalchange.gov/gcis.owl#ConveningLeadAuthor
      http://data.globalchange.gov/gcis.owl#LeadAuthor
      Possibly: http://data.globalchange.gov/gcis.owl#hasCommittee

Caveat: we recognize that the responsibilities of a “convening lead author,” “contributing author,” etc. may differ from report to report.  With few exceptions, the specific nature of those responsibilities is unknown as well.  Please advise whether this would be problematic from a Semantic Web perspective.  Advice is solely what is requested at this time as it will need to be discussed with the entire GCIS Team.

**Comment by zednis** [comment]
I believe all of the examples listed are role instances.

1) Based #128 we are considering moving the role instances out of the ontology and into the DB.  Role instance RDF will subsequently be generated by templates.

2) The role instances we currently have have fairly general definitions.  Some definitions include the text "For NCA3, ..."  I think we could generalize these pretty easily.

example:

```
gcis:ContributingAuthor a prov:Role ;
    rdfs:label "Contributing Author" ;
    skos:editoralNote "Comment content is from: http://www.nesdis.noaa.gov/NCADAC/pdf/nov_16/NCADAC_Mtg_Pres_Nov11_MelRichYoh_Final_111611_7b.pdf" ;
    rdfs:comment "For NCA3, author teams may request people outside of the team to contribute to small sections or text boxes, or to produce graphics." .
```

Since we are looking to remove the role instances from the ontology, how do you prefer we proceed with updating the comments?  We could update the comments in the soon to be removed ontology instances or update the comments as we transition the information to the database.

**Comment by justgo129** [comment]
@aulenbac and @bduggan @rewolfe I'll defer this your way.

**Comment by justgo129** [comment]
Let's resolve #128 and then revisit this one (#101).  I don't now think we even need these roles in the ontology, i.e. leave the turtle templates for values at http://data.globalchange.gov/role_type/ as is.  We relate a document to a person / entity through prov:hadRole in a qualified attribution anyway (i.e. role type as object and not as predicate, see e.g. http://data.globalchange.gov/person/823.thtml).

**Comment by justgo129** [comment]
Is this ready for closure?

**Comment by zednis** [comment]
I think we can close this ticket. Discussions of role subclasses (which I think is what the OP of this ticket is about) can be discussed in #102.

**Comment by justgo129** [comment]
Very good.  Closed #101 on behalf of #102.

**Comment by zednis** [comment]
After reading this ticket again, I think the original question concerned potentially change the comments on the roles to not sound NCA3 specific.

Based on http://data.globalchange.gov/role_type we are not including the comments/descriptions in the generated role instances so I do not think any of the current DB-based role instances would be interpreted as being NCA3-specific and would make sense with non-NCA3 reports.

So, on that note I think we can keep this ticket closed.

We may want to open a new ticket add comments to the role_type instances.

**Comment by justgo129** [comment]
Good call.  I'll defer to @rewolfe.

**Comment by rewolfe** [comment]
Please change the definitions to remove the specific reference to NCA3 (and
draft chapter).  For instance, this current definition
http://data.globalchange.gov/gcis.owl#ReviewEditor :

For NCA3, a review editor is an independent, objective expert who critiques
a draft chapter for scientific accuracy and as appropriately representative.

should be:

A review editor is an independent, objective expert who critiques a draft
publication (or specific subsection of a publication, e.g. chapter) for
scientific accuracy and as appropriately representative.

On Fri, Oct 23, 2015 at 7:48 AM, justgo129 notifications@github.com wrote:

> Good call. I'll defer to @rewolfe https://github.com/rewolfe.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/101#issuecomment-150551408
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
