### ISSUE TITLE
I7 Add the concept of “observation system”

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#104]
Add the concept (class) of “observation system” (alternatively “observing system” or “measurement system”) to allow for aggregation of multiple platform/instruments.  E.g.  NOAA POES is a observation system that includes all of the NOAA-n polar orbiting platforms.

**Comment by xgmachina** [comment]
Quote a definition from Wikipedia 'Earth observation systems consist of instruments and models designed to measure, monitor and predict the physical, chemical and biological aspects of the Earth system' https://en.wikipedia.org/wiki/Global_Earth_Observation_System_of_Systems#Earth_observation_systems 
Do we focus on 'Earth' observation systems here or more general?

**Comment by rewolfe** [comment]
It is interesting that models are included in this definition.  This
doesn't quite match how Observing Systems are being used by OSTP.  For
instance, in the 2014 National Plan for Earth Observation
https://www.whitehouse.gov/sites/default/files/microsites/ostp/NSTC/2014_national_plan_for_civil_earth_observations.pdf,
page 7:

_The term “Earth observations” refers to data and products derived from
Earth observing systems and surveys.The term "observing systems” refers to
one or more sensing elements that directly or indirectly collect
observations of the Earth, measure environmental parameters, or survey
biological or other Earth resources (land surface, biosphere, solid Earth,
atmosphere, and oceans). Sensing elements may be deployed as individual
sensors or in constellations or networks and may include instrumentation or
human elements. Observing system platforms may be mobile or fixed and are
space based, airborne, terrestrial, freshwater, or marine based._

I prefer something closer to this definition.

On Tue, Jul 28, 2015 at 3:33 PM, Marshall.Ma notifications@github.com
wrote:

> Quote a definition from Wikipedia 'Earth observation systems consist of
> instruments and models designed to measure, monitor and predict the
> physical, chemical and biological aspects of the Earth system'
> https://en.wikipedia.org/wiki/Global_Earth_Observation_System_of_Systems#Earth_observation_systems
> Do we focus on 'Earth' observation systems here or more general?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/104#issuecomment-125730193
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by xgmachina** [comment]
I will close the issue since #131 is done.
