### ISSUE TITLE
J9 terms for GCIS entries pertaining to gcmd keywords

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#107]
Please identify or create terms for GCIS entries pertaining to gcmd keywords, e.g.
http://data.globalchange.gov/gcmd_keyword/00fc45e0-400d-4024-a82a-4d6544735f64.html
http://data.globalchange.gov/gcmd_keyword/00fc45e0-400d-4024-a82a-4d6544735f64.thtml

Notably, for the “GCMD Metadata,” “Ancestors,” “gcmd_keywords,” and “parent” fields.  Please advise whether the turtle uses dcterms:subject correctly, as a surrogate for “keyword.”  Per dublin core’s definition (http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-subject):

**Comment by xgmachina** [comment]
Do you mean a property to link a GCIS object to one or more gcmd keywords?

**Comment by zednis** [comment]
:+1: to @xgmachina's question.  If the question is to identify a property to use to associate GCMD keyword concepts with GCIS report content, have you looked at `gcis:subject`?

**Comment by justgo129** [comment]
@xgmachina and @zednis I'm not sure what you're asking.  I'm basically asking to identify the predicates/properties mentioned on a page pertaining to gcmd keywords, e.g. http://data.globalchange.gov/gcmd_keyword/00fc45e0-400d-4024-a82a-4d6544735f64.html
http://data.globalchange.gov/gcmd_keyword/00fc45e0-400d-4024-a82a-4d6544735f64.thtml

for "parent_identifier," "Ancestors," etc..  Some are already provided in the turtle.

I wouldn't consider this a high priority at this point though.

**Comment by xgmachina** [comment]
@justgo129 I think I got what you mean. It is about properties/attributes describing the hierarchical relationships among gcmd keywords. GCMD uses skos as the schema for encoding the hierarchical relationships among keywords, so those properties and information describing 'parent' and 'ancestor' on the html user interface are generated from the skos. I do not see the needs to create new properties for the GCMD keywords.

**Comment by justgo129** [comment]
Works for me.  Closed #107 with no changes made.
