### ISSUE TITLE
role information in the tripelstore appears to be missing

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#123]
@bduggan @justgo129 

When building my query on report chapter contributors I noticed that role labels/descriptions do not appear to be accessible via the endpoint.

Looking at the RDF of the lead author role at http://data.globalchange.gov/role_type/lead_author.thtml it appears there is both a `dcterms:identifier` and `prov:label` for the role instance.  

**NOTE** - that should be `rdfs:label` and not `prov:label`, PROV-O did not define a new label property and suggested the use of `rdfs:label`

If you attempt to select a description of a role you get no results.

```
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?description
WHERE {
  <http://data.globalchange.gov/role_type/lead_author> dcterms:identifier ?role 
}
```

If you do a describe on the instance you do not see any statements where the lead_author instance is the subject (no type information, labels, etc)

```
DESCRIBE <http://data.globalchange.gov/role_type/lead_author>
```

Is it possible that role information is not being imported into the triplestore?

**Comment by zednis** [comment]
To support the theory that role information is not being imported into the triplestore; the following query returns 0 results.

```
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?role
WHERE {
  ?role a prov:Role .
}
```

**Comment by bduggan** [comment]
This will be fixed in the next release (when I run this script)
