### ISSUE TITLE
remove role instances from ontology

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis-ontology#128]
Per discussion in #127.  This issue focuses on defining the role instances in the database and removing the declarations from the ontology

**Comment by zednis** [comment]
@bduggan should we have a related issue in the gcis repository for role instance templates?

**Comment by bduggan** [comment]
On Tuesday, August 25, Stephan Zednik wrote: 

> @bduggan should we have a related issue in the gcis repository for role instance templates?

Yes, also mention adding 'comment' to the database table.
