### ISSUE TITLE
duplicate findingProcess property definition

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#134]
I noticed today that we have 2 definitions for `gcis:findingProcess`.

starting at line 735 in the TTL:

```
gcis:findingProcess a owl:DatatypeProperty ;
    rdfs:label "Finding Process" ;
    rdfs:comment "A finding has a description of the process through which it was derived." ;
    rdfs:domain gcis:Finding ;
    rdfs:range xsd:string .

gcis:findingStatement a owl:DatatypeProperty ;
    rdfs:label "Key finding" ;
    rdfs:comment "The text of the Finding of a Highly Influential Scientific Assessment." ;
    rdfs:domain gcis:Finding ;
    rdfs:range xsd:string .

gcis:findingProcess a owl:DatatypeProperty ;
    rdfs:label "Finding Process" ;
    rdfs:comment "A finding contains a description of the process used in order to reach the Finding." ;
    rdfs:domain gcis:Finding ;
    rdfs:range xsd:string .
```

They are the same except for the slight difference in the comment.  Removing one of them seems straightforward enough.

@justgo129 @rewolfe which comment would like us to retain?

**Comment by justgo129** [comment]
Excellent catch.  I like the second one with the caveat that "it" replaces "the finding" at the end if the label.

**Comment by zednis** [comment]
Pull request created.  I am fine with merging now or waiting for Robert to chime in on the preferred comment.

**Comment by justgo129** [comment]
Let's wait for @rewolfe.  Thanks, @zednis.

**Comment by rewolfe** [comment]
@zednis, I'm okay with @justgo129 recommendation.

On Mon, Aug 24, 2015 at 7:19 PM, justgo129 notifications@github.com wrote:

> Let's wait for @rewolfe https://github.com/rewolfe. Thanks, @zednis
> https://github.com/zednis.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/134#issuecomment-134410148
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by zednis** [comment]
:+1: merging pull request.
