### ISSUE TITLE
Z2. Add startDate and endDate properties with range xsd:date

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#14]
We currently have **gcis:startedAt** and **gcis:endedAt** properties with range dateTime.  If we use these properties for general dates we are forced to include a time value along with the date (e.g. "2012-01-01T00:00:00" when we only want to say "2012-01-01").  I think this may create artificial precision when we just want to talk about a date.  It also forces us to use conventions for dateTime time values for when we don't care about the time.

If there is general agreement that this is something we think we should address I will create a proposal to update the ontology to allow us to additionally support the representation of start and end dates as just dates and not dateTimes.

**Comment by justgo129** [comment]
I am fine with this.

**Comment by zednis** [comment]
| Change Proposal | Z2 |
| :-- | :-: |
| Point of Contact | @zednis |
| Date | 2015-05-26 |

## Proposal

Add **gcis:startDate** and **gcis:endDate** datatype properties with range xsd:date to the ontology.

## Background

The existing **gcis:startedAt** and **gcis:endedAt** properties have range xsd:dateTime.  This causes us to have to encode time information in cases were nothing more than the date is needed.

## Does this change affect the semantics of the ontology?

MOSTLY NO

It does not change any current semantics or inferences.  It does introduce 2 new properties.

## Describe in detail the change being requested

Add **gcis:startDate** and **gcis:endDate** datatype properties with range xsd:date.

## Describe the reason for the change

Provide capability to encode start and end values for temporal extents as dates rather than dateTime values.

## What are the anticipated impacts
- No changes to existing ontology properties or classes
- scripts that generate RDF will have to be updated based on when to use date or dateTime precision
- queries will have to be adjusted to look for date and dateTime precision properties

## What are the risks of not performing the change?

None.

## What is the expected technical effort to support the change?

Expected effort to support the change is low.
- add 2 properties to the ontology
- update instance data scripts to use new properties in cases were date rather than dateTime precision is desirable
- update any queries or processed that used the removed properties

## Describe alternatives considered

We could relax the range of **gcis:startedAt** and **gcis:endedAt** so we could use either xsd:date or xsd:dateTime values with the properties, but then we would have no way to enforce that the value must be some kind of date/dateTime literal.

## Related change proposals

N/A

## Notes

N/A

**Comment by bduggan** [comment]
If we just assume that a time of 00:00:00 GMT means that there is no time information then this is straightforward.   This is probably the case for many of our current datasets.  There is a bigger issue of temporal resolution beyond the '1 day' resolution.  Some datasets have measurements taken weekly, monthly, yearly, biweekly, whatever.  We can sometimes obtain and store this information, but will need to go through some examples to see to what extent it makes sense to apply this information to start/end datetimes.

**Comment by bduggan** [comment]
Two examples:
http://data.globalchange.gov/dataset/nasa-nsidcdaac-0007

> The data were collected every other day

http://data.globalchange.gov/dataset/nasa-podaac-remss-l2p_gridded_25-wsat
http://podaac.jpl.nasa.gov/dataset/REMSS-L2P_GRIDDED_25-WSAT
http://podaac.jpl.nasa.gov/ws/metadata/dataset/?datasetId=PODAAC-GHWST-2GR01&format=gcmd

> Temporal resolution: 12 hours

In both of these the start/end dates are only provided as dates, so I think your proposed change is fine. (for them:  more work should be done looking at other instance data)

**Comment by rewolfe** [comment]
I think this should be okay for the start/end date of datasets.

If we need to specify individual granules (or scenes) or time slices (e.g.
a specific 3 hour period in a weather forecast) we will need the time of
day resolution.  However, I can't think of a specific case where this might
be relevant to GCIS.

On Tue, Jun 9, 2015 at 8:48 AM, Brian Duggan notifications@github.com
wrote:

> Two examples:
> http://data.globalchange.gov/dataset/nasa-nsidcdaac-0007
> 
> The data were collected every other day
> 
> http://data.globalchange.gov/dataset/nasa-podaac-remss-l2p_gridded_25-wsat
> http://podaac.jpl.nasa.gov/dataset/REMSS-L2P_GRIDDED_25-WSAT
> 
> http://podaac.jpl.nasa.gov/ws/metadata/dataset/?datasetId=PODAAC-GHWST-2GR01&format=gcmd
> 
> Temporal resolution: 12 hours
> 
> In both of these the start/end dates are only provided as dates, so I
> think your proposed change is fine.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/14#issuecomment-110346450
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by aulenbac** [comment]
It is relevant to GCIS. It is relevant to the science. GCIS is a tool to aid people making science-based decisions. Examples? Think of any question which addresses a diurnal cycle -- changes in stream flow or forest respiration or particulate levels or carbon monoxide levels or traffic patterns and so on. Or any query which needs to know if a peak or trough event occurred within the period of record. Think floods or economic downturns. 

Why are we dumbing down the system? Why aren't we following a common practice like ISO 8601? It is an international standard for exchanging date and time information. GCIS is about the exchanging of information. ISO 8601 allows the exchange of dates (2015-06-09), combined data and time in UTC (and sometimes we need time zones), weeks (2015-W24), and day of year (2015-160).

**Comment by zednis** [comment]
@aulenbac adding the proposed properties is not dumbing down the system and still uses date information expressed in ISO-8601.

We are not losing any current expressivity but introducing a property that can be used to express dates without the convention that dates with no time information are expressed as datetime values with "00:00:00" time components.  

I feel that in cases where we only wish to specify a date, we should use xsd:date, and not xsd:datetime with the implicit assumption that "00:00:00" doesn't matter.

**Comment by bduggan** [comment]
On Tuesday, June  9, Stephan Zednik wrote: 

> I feel that in cases where we only wish to specify a date, we should use a xsd:date, and not a xsd:datetime with the implicit assumption that "00:00:00" doesn't matter.

Agreed.  Generally, the 00:00:00 is incorrect since it was not
in the original data.  There may be some additional changes to
the relational model to support making the distinction and preserving
fidelity in the instance data, but I think adding xsd:date to the
ontology is the right thing to do.

Therefore :+1:

Brian

**Comment by zednis** [comment]
I updated the issue name to reduce confusion.

**Comment by rewolfe** [comment]
Yes, +1

On Tue, Jun 9, 2015 at 1:35 PM, Brian Duggan notifications@github.com
wrote:

> On Tuesday, June 9, Stephan Zednik wrote:
> 
> > I feel that in cases where we only wish to specify a date, we should use
> > a xsd:date, and not a xsd:datetime with the implicit assumption that
> > "00:00:00" doesn't matter.
> 
> Agreed. Generally, the 00:00:00 is incorrect since it was not
> in the original data. There may be some additional changes to
> the relational model to support making the distinction and preserving
> fidelity in the instance data, but I think adding xsd:date to the
> ontology is the right thing to do.
> 
> Therefore :+1:
> 
> Brian
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/14#issuecomment-110441942
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
