### ISSUE TITLE
J2. Anchor tags and HTML build process

### ISSUE THREAD

**Issue by bduggan** [USGCRP/gcis-ontology#16]
The rendered ontology at http://data.globalchange.gov/gcis.owl does not have proper support for anchor tags, e.g. this

 http://data.globalchange.gov/gcis.owl#Dataset

doesn't jump to this section of the page:

 http://data.globalchange.gov/gcis.owl#d4e1684

**Comment by justgo129** [comment]
Good point.  It's also in the ontology improvements document so we can cross it off when resolved.

**Comment by xgmachina** [comment]
Some useful information: http://www.w3.org/TR/swbp-vocab-pub/

**Comment by zednis** [comment]
For reference the OWL HTML documentation was generated using the Live OWL Documentation Environment - http://www.essepuntato.it/lode

We should probably also include this HTML in the repository and update it each time we make a change to the ontology.

**Comment by bduggan** [comment]
It would be great to have that; I could then include the latest tagged version whenever there is a new GCIS release.

**Comment by zednis** [comment]
I'll work with @lic10 to add doc/gcis.html to this repository based on the most current version of the ontology in github.  For now we'll have a convention to re-generate the HTML every time we update the ontology.  I'll also look into github hooks that might be able to do that for us automatically

edit - while working on the versioned HTML we will make sure the anchor tags work as desired.

**Comment by bduggan** [comment]
Great!

**Comment by bduggan** [comment]
I'm updating the title of this, and changing the importance.  I will wait for this to be resolved before pulling from the gcis-ontology to the gcis repository.  That way changes to gcis.ttl in production will be consistent with changes to the HTML rendering.

**Comment by bduggan** [comment]
Looks like the HTML can be generated by just adding the ontology URL to
`http://www.essepuntato.it/lode/owlapi/`
like this: http://www.essepuntato.it/lode/owlapi/https://raw.githubusercontent.com/USGCRP/gcis-ontology/master/gcis.ttl

**Comment by rewolfe** [comment]
Cool!

On Tue, Jul 7, 2015 at 12:22 PM, Brian Duggan notifications@github.com
wrote:

> Looks like the HTML can be generated by just adding the ontology URL to
> http://www.essepuntato.it/lode/owlapi/
> like this:
> http://www.essepuntato.it/lode/owlapi/https://raw.githubusercontent.com/USGCRP/gcis-ontology/master/gcis.ttl
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/16#issuecomment-119259538
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by zednis** [comment]
@bduggan yep, but the anchor tag issue is still there on the generated HTML.  We may have to do some post-processing of the HTML to get the anchor behavior we want.

**Comment by bduggan** [comment]
Good catch.
I'd like to do a push this week, and since the templates are now using terms from the latest ontology, I've copied over gcis.ttl and regenerated gcis.owl ( usgcrp/gcis@e4ff7f5d1938a537c63e47cb4433dc0e1952e43d) with a little script that pulls from github and lode (usgcrp/gcis@516a14dd40830de4ad7e0d2661489547210f6b1f).

**Comment by bduggan** [comment]
The above script adds a decent process to pull changes, (e.g. see usgcrp/gcis@dfd0ca742df682e982f32110adf36b75f8c12229), so I'm removing the 'critical' tag from this issue.

**Comment by congruili** [comment]
in the production HTML file:
<a href="#d4e1684" title="http://data.globalchange.gov/gcis.owl#Dataset"..

should be changed to:
<a href="#Dataset" title="http://data.globalchange.gov/gcis.owl#Dataset"..

A practical way is to write a script to modify all the situations like this in the HTML file.

**Comment by zednis** [comment]
@lic10 would you be willing to take the lead on writing that script?

**Comment by congruili** [comment]
will try.

**Comment by bduggan** [comment]
Also the <div id="d4e1684"..  portions need to be changed:
https://github.com/USGCRP/gcis/blob/master/lib/Tuba/files/public/gcis.owl#L210

**Comment by justgo129** [comment]
@lic10 @zednis what is the progress on this issue?

**Comment by zednis** [comment]
@bduggan We have a python script that will fix the anchor tags in the generated HTML.  Where do you think we should add it?  How about a /scripts directory in this repository?

**Comment by bduggan** [comment]
On Friday, July 24, Stephan Zednik wrote: 

> @bduggan We have a python script that will fix the anchor tags in the generated HTML.  Where do you think we should add it?  How about a /scripts directory in this repository?

Sure, sounds fine.

Brian

**Comment by justgo129** [comment]
Closed #16 due to #98.
