### ISSUE TITLE
BUILD TESTS ARE FAILING

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#168]
There appear to have been recent merges to the unit tests that are causing the build tests to fail.

Tests related to tickets #113 and #118 are failing.

Please DO NOT merge branches that do not pass the Travis-CI tests.

https://travis-ci.org/USGCRP/gcis-ontology/builds/89064364

```
ok 1 - valid gcis.ttl
ok 2 - 01-basic-csv.sparql
ok 3 - 01-basic.sparql
ok 4 - 02-report.sparql
ok 5 - 03-classes-as-properties.sparql
ok 6 - 04-capitalization.sparql
not ok 7 - missing results/113-author-nca3.txt or 113-author-nca3.csv
# /tmp/113-author-nca3.txt:
# --------------------------------------------------------------------------------------------------------------------------------
# | ContributorID                              | Name                  | Role          | ChapterName             | ChapterNumber |
# ================================================================================================================================
# | <http://data.globalchange.gov/person/1010> | "Franco, Guido"       | "Lead Author" | "Energy Supply and Use" | "4"           |
# | <http://data.globalchange.gov/person/4015> | "Weyant, John P."     | "Lead Author" | "Energy Supply and Use" | "4"           |
# | <http://data.globalchange.gov/person/950>  | "Wilbanks, Thomas J." | "Lead Author" | "Energy Supply and Use" | "4"           |
# | <http://data.globalchange.gov/person/986>  | "Richels, Rich"       | "Lead Author" | "Energy Supply and Use" | "4"           |
# | <http://data.globalchange.gov/person/987>  | "Newell, Richard G."  | "Lead Author" | "Energy Supply and Use" | "4"           |
# --------------------------------------------------------------------------------------------------------------------------------
# /tmp/113-author-nca3.csv:
# ContributorID,Name,Role,ChapterName,ChapterNumber
# http://data.globalchange.gov/person/1010,"Franco, Guido",Lead Author,Energy Supply and Use,4
# http://data.globalchange.gov/person/4015,"Weyant, John P.",Lead Author,Energy Supply and Use,4
# http://data.globalchange.gov/person/950,"Wilbanks, Thomas J.",Lead Author,Energy Supply and Use,4
# http://data.globalchange.gov/person/986,"Richels, Rich",Lead Author,Energy Supply and Use,4
# http://data.globalchange.gov/person/987,"Newell, Richard G.",Lead Author,Energy Supply and Use,4
not ok 8 - missing results/118-authorORCiDs.txt or 118-authorORCiDs.csv
Encountered " "as" "as "" at line 13, column 9.
Was expecting one of:
    <VAR1> ...
    <VAR2> ...
    "from" ...
    "where" ...
    "(" ...
    "{" ...

The command "./run-tests.sh" exited with 2.
Done. Your build exited with 1.
```

**Comment by justgo129** [comment]
Yep, this relates to the issue with Virtuoso we broached yesterday.  We get the same errors.

**Comment by zednis** [comment]
This can't be related to virtuoso; running virtuoso is not part of the built tests for gcis-ontology.

**Comment by justgo129** [comment]
I think we'll need to debug more offline as @rewolfe and I spent quite a lot of time dealing with this yesterday when preparing another branch for merging.  Let's table all merge requests until a later point.  @rewolfe @zednis

**Comment by rewolfe** [comment]
@zednis and @justgo129 - I agree that this is a different gYear issue than
we were debugging in Virtuoso yesterday.  That Virtuoso issue had to do
with trying some scripts that used to work against Virtuoso not working any
longer because of changes in the ontology.  Sorry for the confusion.

On Tue, Nov 3, 2015 at 1:42 PM, justgo129 notifications@github.com wrote:

> I think we'll need to debug more offline as @rewolfe
> https://github.com/rewolfe and I spent quite a lot of time dealing with
> this yesterday when preparing another branch for merging. Let's table all
> merge requests until a later point. @rewolfe https://github.com/rewolfe
> @zednis https://github.com/zednis
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/168#issuecomment-153449868
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
Okay, I know the issue.  It's the lack of a .txt suffix for the last file listed at:
https://github.com/USGCRP/gcis-ontology/tree/master/t/results

This is actually resolved in the branch on which I was working yesterday, but I am unable to merge that branch because of the (unrelated) issues with Virtuoso yesterday; the tests failed.  I don't want to create a merge conflict by changing the suffix of "ticket118..." manually though.  Any suggestions?

**Comment by justgo129** [comment]
To see the tweak made in my branch, go to:
https://github.com/USGCRP/gcis-ontology/tree/justgo129-patch-1/t/results

(Note there are 31 commits there,hence my concern about potential merge errors with just making one tweak).

**Comment by zednis** [comment]
There were a large number of direct to master commits on the 28th and 29th that broke the build.

https://travis-ci.org/USGCRP/gcis-ontology/builds

please, please, do not merge branches that do not pass the tests.

My inclination right now is to revert all changes that have been made to master since the 28th.

**Comment by justgo129** [comment]
Please no reverts at this time.

**Comment by justgo129** [comment]
To clarify: we weren't able to merge yesterday because the potential merges failed the unit tests.

**Comment by zednis** [comment]
so we revert the changes to master that originally broke the build

**Comment by justgo129** [comment]
I'm not wild about that given the intervening changes.  Let's discuss further offline so I can be sure to pinpoint what we're doing.  Closed #168.

**Comment by justgo129** [comment]
Please add this to the agenda for today's meeting.

**Comment by zednis** [comment]
This is the process we should be following: https://guides.github.com/introduction/flow/
- All commits should be done to a branch
- branches should only be merged into master if they pass all tests
- pull requests act as code reviews for proposed merges

**Comment by rewolfe** [comment]
Stephan, I agree. Is there a way to set up a GitHub policy that enforces
this? -Robert

On Tue, Nov 3, 2015 at 2:52 PM, Stephan Zednik notifications@github.com
wrote:

> This is the process we should be following:
> https://guides.github.com/introduction/flow/
> - All commits should be done to a branch
> - branches should only be merged into master if they pass all tests
> - pull requests act as code reviews for proposed merges
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/168#issuecomment-153468725
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by zednis** [comment]
I don't think so, not without limiting commit access to a single user and forcing everyone to suggest changes via pull requests from downstream forks.

**Comment by zednis** [comment]
As far as I can tell enforcement of github flow is mostly upheld by social contract and having admins that liberally revert commits that don't follow the process :-)

**Comment by rewolfe** [comment]
Got it.  Thanks.

On Tue, Nov 3, 2015 at 2:59 PM, Stephan Zednik notifications@github.com
wrote:

> As far as I can tell enforcement of github flow is mostly upheld by social
> contract and having admins that liberally revert commits that don't follow
> the process :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/168#issuecomment-153470532
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by zednis** [comment]
I pushed a commit to master that reverted several commits from the 28th and 29th.  The master branch is now building successfully again.  I also created a new branch 'update-run-tests-script' and made an initial commit to it to use a OS/X compatible diff call.

**Comment by justgo129** [comment]
Excellent - thanks, @zednis.  Please feel free close to #168 when you feel the time is right.

**Comment by zednis** [comment]
The master branch is passing build tests again.  Closing this ticket.
