### ISSUE TITLE
J1. IRI for organization ontology

### ISSUE THREAD

**Issue by congruili** [USGCRP/gcis-ontology#24]
The IRI for organization ontology seems to be incorrect as listed at the page at http://data.globalchange.gov/gcis.owl .That page lists the IRI of http://www.w3.org/ns/org/ but per Section 4 ("Namespaces") of the page at http://www.w3.org/TR/vocab-org/ it is http://www.w3.org/ns/org#

**Comment by justgo129** [comment]
Thanks for taking this on.

**Comment by congruili** [comment]
We should just change the IRI into http://www.w3.org/ns/org# in production.

**Comment by justgo129** [comment]
Fine with me.

**Comment by bduggan** [comment]
On Tuesday, June 30, lic10 wrote: 

> We should just change the IRI into http://www.w3.org/ns/org/# in production. 

I will push, once issue #16 is resolved.

**Comment by congruili** [comment]
pull request sent
