### ISSUE TITLE
J5. definition of "Scenario"

### ISSUE THREAD

**Issue by congruili** [USGCRP/gcis-ontology#25]
Revisit definition for http://data.globalchange.gov/gcis.owl#d4e2042 to ensure continued accuracy.  This URL points to "Scenario" in the GCIS Ontology.

**Comment by justgo129** [comment]
I think this will be of assistance:
http://scenarios.globalchange.gov/content/scenarios

But I'd be hesitant to link anything directly to the NCA3 to minimize later improvements to the ontology.

**Comment by zednis** [comment]
Looking at the ontology I noticed a typo in `gcis:describesScenario`.  Proposing fix with #26

**Comment by zednis** [comment]
1) Should we change the name of `gcis:isDescribedIn` to be less general?  It is specific to scenarios and reports which would not be clear from the name/URI or label.

2) Should `gcis:describesScenario` and `gcis:isDescribedIn` be inverse properties?

**Comment by zednis** [comment]
@justgo129 has mentioned in #26 that the domain and ranges of the properties should probably be re-evaluated.  I agree with him on this.

**Comment by justgo129** [comment]
I'm fine having gcis:describesScenario gcis:isDescribedIn be inverse properties.

**Comment by justgo129** [comment]
fyi I just fixed another xsd:Scenario.
https://github.com/USGCRP/gcis-ontology/pull/27
https://github.com/USGCRP/gcis/pull/180

**Comment by zednis** [comment]
Current definition of `gcis:Scenario` class.

```
gcis:Scenario a owl:Class ;
    rdfs:label "Scenario" ;
    rdfs:comment "A coherent description of a potential future situation that serves as input to more detailed analyses or modeling. Scenarios are tools that explore, 'if�, then�.' statements, and are not predictions of or prescriptions for the future." ;
```

@justgo129 @rewolfe  are there any outstanding questions regarding the accuracy of this definition?  Have any comments/concerns been raised?

**Comment by justgo129** [comment]
I can check on this.

**Comment by justgo129** [comment]
Also, @zednis could you please clarify the meaning behind the special characters in the defn?  Thanks.

**Comment by justgo129** [comment]
To follow up, I've been informed that either (1) this definition, that at (2) http://scenarios.globalchange.gov/content/scenarios, or that at (3) http://www.globalchange.gov/climate-change/glossary would be acceptable for use in our ontology.  As such, I propose going with (3) since it appears in the official glossary on globalchange.gov.

**Comment by justgo129** [comment]
Seeing no objections, let's go with (3).  Pull request forthcoming.

**Comment by justgo129** [comment]
Closed via:
https://github.com/USGCRP/gcis-ontology/pull/87

Closing https://github.com/USGCRP/gcis-ontology/issues/25.
