### ISSUE TITLE
Possible updates to describesScenario property

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#28]
proposal: 
1) remove domain from `gcis:describesScenario`
2) rename `gcis:isDescribedIn` to `gcis:scenarioDescribedIn`
2) remove range from `gcis:scenarioDescribedIn`
4) make `gcis:describesScenario` and `gcis:scenarioDescribedIn` inverse properties

**Comment by zednis** [comment]
@justgo129 @bduggan what do you think of the proposed changes to the properties related to Scenario?

**Comment by justgo129** [comment]
I'm fine if @bduggan is fine with it.

On Mon, Jul 13, 2015 at 11:37 AM, Stephan Zednik notifications@github.com
wrote:

> @justgo129 https://github.com/justgo129 @bduggan
> https://github.com/bduggan what do you think of the proposed changes to
> the properties related to Scenario?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/28#issuecomment-121017732
> .

## 

---

Justin Goldstein, Ph.D.
Advance Science Climate Data and Observing Systems Coordinator
US Global Change Research Program
1717 Pennsylvania Ave NW, Suite #250
Washington, DC 20006

O: (202) 419-3496
M: (202) 285-3005

e-mail: jgoldstein AT usgcrp Dot gov
http://www.globalchange.gov

**Comment by bduggan** [comment]
Yes, sounds good.

**Comment by justgo129** [comment]
Great, we're done with this Issue (#28).  @zednis please feel free to close this issue and any other related issues, merging related pull requests if necessary.

**Comment by zednis** [comment]
thanks @justgo129

**Comment by zednis** [comment]
@bduggan I did a search and did not find `gcis:describesScenario` or the old `gcis:describedIn` in any of the RDF templates.  If my search was accurate then I do not think this ontology change will require any template updates.

**Comment by bduggan** [comment]
I don't see describesScenario or describedIn either.
