### ISSUE TITLE
B.1. Dates relevant to the lifecyle of a dataset

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#31]
The google doc item B.1.: 
Apply any Dublin Core terms (http://purl.org/dc/terms) or existing GCIS ontology terms to reflect the access and release dates of datasets.

**Comment by xgmachina** [comment]
Dublin Core terms (http://purl.org/dc/terms) has a few date properties that apply to Dataset: `date`, `dateAccepted`, `dateCopyrighted`, `dateSubmitted`. 
Schema.org (http://schema.org/Dataset) also has a few date properties for Dataset: `dateCreated`, `dateModified`, `datePublished`. It also has a property `releasedEvent` which points to a `PublicationEvent`.
I think a purpose here is to record dates of milestones in the life cycle of a dataset. We can have similar properties in GCIS ontology, or reuse those existing ones in Dublin Core, schema.org and others. @justgo129 and @aulenbac, can you take a view of the above properties and comment which ones make sense, and do we need more besides those?

**Comment by zednis** [comment]
for reference an RDF schema of schema.org terms is available at http://schema.rdfs.org/all.ttl

**Comment by zednis** [comment]
What is the scenario / use case for encoding the access date of a dataset?  That may be a case where we can leverage PROV.

**Comment by xgmachina** [comment]
I am also curious about this. @justgo129 do you have any comments or user stories on the `accessDate` of Dateset?

**Comment by justgo129** [comment]
Sorry, I don't have any use cases although I definitely see the importance of getting this right.  I'll defer to @aulenbac

**Comment by justgo129** [comment]
@xgmachina in your comment beginning with "Dublin Core terms," are you asking for @aulenbac and me to review the properties that exist in the gcis ontology or those in dublin core?

**Comment by xgmachina** [comment]
@justgo129 and @aulenbac I reviewed the gcis ontology and found we used `dct:issued` and `dct:modified` to describe datasets. The two properties both represent dates according to their labels 'Date Issued' and 'Date Modified'. And I even found more date relevant properties `dct:created`, `dct:available`, and `dct:valid`. They just do not have 'date' in the property name but all have 'date' in the label. 

Now let's put those all together and see if we can pick up a list of properties that can describe dates relevant to key steps in the lifecycle of a dataset:

Dublin Core terms: `dct:issued`, `dct:modified`, `dct:created`, `dct:available`, `dct:valid`, `dateAccepted`, `dateCopyrighted`, `dateSubmitted` .
Schema.org: `schema:dateCreated`, `schema:dateModified`, `schema:datePublished`. 

I can see that the three schema.org properties are all covered in the dct terms (`schema:datePublished` is corresponding to `issued`). Then we can focus on the dct terms. Seems those terms are from the perspective of data providers. In your original description of the issue, do you want to add a few 'date' terms that are from the perspective of data users, such as `accessDate`?

**Comment by justgo129** [comment]
"In your original description of the issue, do you want to add a few 'date' terms that are from the perspective of data users, such as accessDate?"

   @xgmachina please clarify whether you'd like @aulenbac and me to suggest new terms for the ontology or identify potential uses for existing ones and add them to the aforementioend document.  Thanks!

**Comment by justgo129** [comment]
Given the lack of activity on this issue #31, I'm closing it.
