### ISSUE TITLE
D2. property for publication year

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#33]
from https://docs.google.com/document/d/1KSfdbp9Nf1kzuvoAtWo3Qhs_m-ocuafpIv9nSM3YlPA/edit

> Something is needed for “publication_year” since not available at dublin core.  Can be of format xsd:gYear, synonymous with dcterms:date and http://rs.tdwg.org/dwc/terms/index.htm#year  (which is dwc:Year, the term we are currently using).

**Comment by xgmachina** [comment]
@zednis do you mean the range of publication_year or a property for it?

**Comment by zednis** [comment]
Err, the text in the first comment is pulled directly from the ontology suggestion google doc.  I have updated the comment to make the source of the issue more clear.

As for the request - my guess is there is a desire for something like this:

```
ex:publication1 gcis:publicationYear "2015"^^xsd:gYear .
```

I think this is sensible and I would approve of its addition if we cannot find a suitable property in a commonly used publication-related vocabulary.

**Comment by justgo129** [comment]
Meant as a property for it, similar to the latest example by @zednis

**Comment by xgmachina** [comment]
`dct:issued` has a meaning close to 'date published', but not specifically 'year'. So if we address 'year' I will support @zednis

**Comment by zednis** [comment]
@xgmachina I reached the same conclusion for the same reasons

**Comment by justgo129** [comment]
I'd be fine with that.  The same concern about dct:issued prompted the initial question, actually.  Assuming we go with a gcis:publicationYear or something similar thereof, is there a way we can relate it to existing terms in other vocabularies/ontologies?  I'd be all right if not but it would be great if we could.

**Comment by zednis** [comment]
@justgo129 the question isn't can we relate it to terms in other vocabularies/ontologies, the question is are there terms in other ontologies that we should relate it to?

**Comment by justgo129** [comment]
Let's go with gcis:publication year or a variation thereof, and ascertain whether predicates from other ontologies can be related to gcis:publicationYear.

**Comment by justgo129** [comment]
Addressed at:
https://github.com/USGCRP/gcis/pull/200

Once merged, we can close #33.

**Comment by justgo129** [comment]
Closed #33 due to merged https://github.com/USGCRP/gcis/pull/200.
