### ISSUE TITLE
D3. Should we add Book, Webpage, Article, and Journal as subclasses of Publication?

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#34]
Since we have gcis:Report, gcis:Image, and gcis:Figure, should we also have gcis:Book, gcis:Webpage, gcis:Article, and gcis:Journal, and make these all subclasses of their respective terms in the bibo ontology?

**Comment by xgmachina** [comment]
If there are instance records of those classes in GCIS, or potential of them in the future, I will support to add them.

**Comment by justgo129** [comment]
We have all those.

**Comment by xgmachina** [comment]
Do we want more subclasses of gcis:Publication. e.g., Standard, Map, etc. See subclasses of bibo:Document at:
http://www.essepuntato.it/lode/owlapi/http://bibliontology.com/bibo/bibo.php#d4e2399

**Comment by justgo129** [comment]
I think is all we'd need (or borrow from bibo or another source if acceptable given domain/ranges etc.):

gcis:Book
gcis:Webpage
gcis:Article
gcis:Journal

As we have gcis:Dataset, gcis:Table, and gcis:Array.

We may also need a gcis:Generic down the road but I wouldn't worry about it now.

**Comment by zednis** [comment]
What would `gcis:Generic` be?

**Comment by rewolfe** [comment]
I think it makes sense to go ahead and include gcis:Generic now because we
already have a number of publications that fall into this category.

On Mon, Jul 6, 2015 at 10:55 AM, justgo129 notifications@github.com wrote:

> I think is all we'd need (or borrow from bibo or another source if
> acceptable given domain/ranges etc.):
> 
> gcis:Book
> gcis:Webpage
> gcis:Article
> gcis:Journal
> 
> As we have gcis:Dataset
> 
> We may also need a gcis:Generic down the road but I wouldn't worry about
> it now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/34#issuecomment-118879780
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
We've been using generics to describe publication types that aren't one of the following: dataset, book (or book section), article, webpage, report.  These may include conference proceedings, conference papers, theses, etc.

**Comment by zednis** [comment]
I do not think we should use the class `gcis:Generic`.

**Comment by bduggan** [comment]
I agree -- :-1: for gcis:Generic

**Comment by rewolfe** [comment]
What is an alternative proposal for these items (the ones that Justin
mentioned).

On Mon, Jul 6, 2015 at 12:11 PM, Brian Duggan notifications@github.com
wrote:

> I agree -- [image: :-1:] for gcis:Generic
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/34#issuecomment-118911898
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by bduggan** [comment]
Just define them as gcis:Publications, but no subclass since the nature of these objects is not defined.

**Comment by zednis** [comment]
@rewolfe  I assume you are referring to: conference proceedings, conference papers, theses, etc.

In cases where none of the current subclasses of `gcis:Publication` are appropriate I think we should give the instance type `gcis:Publication` and make a point to evaluate if a new subclass should be defined.  We can then go back and update the template to include the new subclass as needed.

The one area where this ~may~ cause complications is in the RESTful API.

What I don't think makes sense is to type something as `gcis:Generic` and then possibly go back later and change it to `gcis:ConferencePaper`.

There are a couple of reasons I do not like `gcis:Generic`
- it does not follow the open-world assumption
- it is an unnecessary closure of the possible subclasses of `gcis:Publication`.
- If we add a new subclass of `gcis:Publication` we will be inclined to change the type of some instances from `gcis:Generic` to the new type - this is a fundamentally different update then they had just had type `gcis:Publication`.

**Comment by zednis** [comment]
:+1:  to @bduggan's phrasing

**Comment by rewolfe** [comment]
+1 : works for me

**Comment by xgmachina** [comment]
Classes added: #37 
gcis:Book
gcis:Webpage
gcis:Article
gcis:Journal

**Comment by justgo129** [comment]
Could we make the ferns for gcis:Article and gcis:Book more specific to GCIS content?  For instance, GCIS contains some ebooks.  We use articles specifically to refer to journal articles.

**Comment by justgo129** [comment]
Terms, I mean

**Comment by justgo129** [comment]
In the meantime, I revised the turtle templates appropriately to reflect the new terms:

https://github.com/USGCRP/gcis/pull/183

**Comment by xgmachina** [comment]
@justgo129 I think a ebook is also a `gcis:Book`. Journal/academic articles and magazine articles are `gcis:Book`. Do you mean we need `gcis:eBook` and `gcis:JournalArticle`? bibo does have a class `bibo:AcademicArticle`

**Comment by zednis** [comment]
I agree with @xgmachina that ebooks are just books.  If there are extra properties that make sense for ebooks and not all books then I could see the justification for an ebook class (which would be a subclass of book), but otherwise I would just use the class Book to represent both physical books and ebooks.

**Comment by justgo129** [comment]
Let me clarify: I agree that ebooks should be classified as books.  My concern is that the definition for a gcis:Book is restrictive against ebooks.  I suggest broadening the definition.  Sorry for my lack of clarity.

**Comment by xgmachina** [comment]
Thanks @justgo129 I made a few updates to the content of rdfs:comment of `gcis:Book` and `gcis:Article` see #55

**Comment by justgo129** [comment]
See:
https://github.com/USGCRP/gcis-ontology/pull/63

#55 is now closed.

**Comment by justgo129** [comment]
#65 should now work.  If it's acceptable, we can close this issue, as well as #55 and #63 .  These were the changes which @xgmachina and @justgo129 discussed today.

**Comment by justgo129** [comment]
Corresponding pull request: #65.  Please ignore all other outstanding pull requests pertaining to this topic.
