### ISSUE TITLE
I3. representing "Also known as" in lexicons

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#36]
Please create something for “also known as” (see e.g. http://data.globalchange.gov/instrument/topex-microwave-radiometer)

**Comment by zednis** [comment]
@justgo129 Can you provide more information on the problem?

Also, there is currently a "Also known as" section in the generated RDF.

from http://data.globalchange.gov/instrument/topex-microwave-radiometer.thtml

```
## Also known as:
<http://data.globalchange.gov/instrument/topex-microwave-radiometer>
   skos:altLabel "763";
   gcis:hasURL "http://database.eohandbook.com/database/instrumentsummary.aspx?instrumentID=763";
   skos:exactMatch <http://data.globalchange.gov/lexicon/ceos/instrumentID/763> .
<http://data.globalchange.gov/instrument/topex-microwave-radiometer>
   skos:altLabel "TMR";
   gcis:hasURL "http://database.eohandbook.com/database/instrumentindex.aspx#T";
   skos:exactMatch <http://data.globalchange.gov/lexicon/ceos/Instrument/TMR> .
<http://data.globalchange.gov/instrument/topex-microwave-radiometer>
   skos:altLabel "c1a69b2c-52ff-4eb3-8e29-f1aaf5c0733c";
   gcis:hasURL "http://gcmdservices.gsfc.nasa.gov/static/kms/concept/c1a69b2c-52ff-4eb3-8e29-f1aaf5c0733c";
   skos:exactMatch <http://data.globalchange.gov/lexicon/gcmd/instrument/c1a69b2c-52ff-4eb3-8e29-f1aaf5c0733c> .
<http://data.globalchange.gov/instrument/topex-microwave-radiometer>
   skos:altLabel "TOPEX MICROWAVE RADIOMETER";
   skos:exactMatch <http://data.globalchange.gov/lexicon/podaac/Sensor/TOPEX%20MICROWAVE%20RADIOMETER> .
```

**Comment by justgo129** [comment]
Sure.  The issue was representing the "also known as" representation in the
html.  See:
http://data.globalchange.gov/instrument/topex-microwave-radiometer

on the bottom left above "instrumentID 763".

I believe recent changes have made this moot.  e.g.:
http://data.globalchange.gov/instrument/topex-microwave-radiometer.thtml

Please confirm, and if so, feel free to close.

On Wed, Jul 1, 2015 at 3:23 PM, Stephan Zednik notifications@github.com
wrote:

> @justgo129 https://github.com/justgo129 Can you provide more
> information on the problem?
> 
> Also, there is currently a "Also known as" section in the generated RDF.
> 
> from
> http://data.globalchange.gov/instrument/topex-microwave-radiometer.thtml
> 
> ## Also known as:
> 
> http://data.globalchange.gov/instrument/topex-microwave-radiometer
>    skos:altLabel "763";
>    gcis:hasURL "http://database.eohandbook.com/database/instrumentsummary.aspx?instrumentID=763";
>    skos:exactMatch http://data.globalchange.gov/lexicon/ceos/instrumentID/763 .
> http://data.globalchange.gov/instrument/topex-microwave-radiometer
>    skos:altLabel "TMR";
>    gcis:hasURL "http://database.eohandbook.com/database/instrumentindex.aspx#T";
>    skos:exactMatch http://data.globalchange.gov/lexicon/ceos/Instrument/TMR .
> http://data.globalchange.gov/instrument/topex-microwave-radiometer
>    skos:altLabel "c1a69b2c-52ff-4eb3-8e29-f1aaf5c0733c";
>    gcis:hasURL "http://gcmdservices.gsfc.nasa.gov/static/kms/concept/c1a69b2c-52ff-4eb3-8e29-f1aaf5c0733c";
>    skos:exactMatch http://data.globalchange.gov/lexicon/gcmd/instrument/c1a69b2c-52ff-4eb3-8e29-f1aaf5c0733c .
> http://data.globalchange.gov/instrument/topex-microwave-radiometer
>    skos:altLabel "TOPEX MICROWAVE RADIOMETER";
>    skos:exactMatch http://data.globalchange.gov/lexicon/podaac/Sensor/TOPEX%20MICROWAVE%20RADIOMETER .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/36#issuecomment-117800180
> .

## 

---

Justin Goldstein, Ph.D.
Advance Science Climate Data and Observing Systems Coordinator
US Global Change Research Program
1717 Pennsylvania Ave NW, Suite #250
Washington, DC 20006

O: (202) 419-3496
M: (202) 285-3005

e-mail: jgoldstein AT usgcrp Dot gov
http://www.globalchange.gov

**Comment by zednis** [comment]
@bduggan can you confirm that this issue is closable?

**Comment by bduggan** [comment]
On Tuesday, July  7, Stephan Zednik wrote: 

> @bduggan can you confirm that this issue is closable?

Yes, as far as I can see the current treatment is consistent with
(and has some redundancy with) the treatment in usgcrp/gcis#165.

**Comment by justgo129** [comment]
Works for me.  Closing due to the reasons stated above.
