### ISSUE TITLE
Make rdfs:labels lower case.

### ISSUE THREAD

**Issue by bduggan** [USGCRP/gcis-ontology#38]
See #21

**Comment by justgo129** [comment]
@zednis what is the status of this effort?

**Comment by justgo129** [comment]
@bduggan  / @zednis are we good to close #38?

**Comment by zednis** [comment]
busy today but I will try to check on this.

**Comment by zednis** [comment]
Not all properties have had their labels updated.  I will make a pull request with some more label updates.
