### ISSUE TITLE
Fix travis build process

### ISSUE THREAD

**Issue by bduggan** [USGCRP/gcis-ontology#47]
There is currently a syntax error in gcis.ttl -- line 569 of gci.ttl should be a . not a ;.
riot is catching this but the exit status is not correct, so the build is passing incorrectly:

https://travis-ci.org/USGCRP/gcis-ontology/builds/69893063

**Comment by bduggan** [comment]
Note in this case the build failure means the issue was resolved.

**Comment by zednis** [comment]
I have fixed the incorrect semicolon in the RDF.
