### ISSUE TITLE
SPARQL queries

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis-ontology#5]
Hi @zednis ,
  We earlier discussed the need for the list of SPARQL queries which are integrated into GCIS.  Are you referring to  the ones integrated at https://github.com/USGCRP/gcis/blob/master/t/011_sparql.t or just a list of other queries that we've successfully tried?

**Comment by zednis** [comment]
I was not referring to any specific suites of queries because I did not know what already existed.  I think it will be important to have a test suite of queries that can be executed by Travis CI when commits are made to the repository.

**Comment by justgo129** [comment]
I fully agree.  If you have a couple of minutes, could you look at the code linked to above and let me know if you'd like to see some additional sample queries?  Also copying @bduggan on this.

**Comment by justgo129** [comment]
Hi everyone, I'm elevating the priority of this ticket due to our recent discussion, and rephrasing it from a question to a request for additional SPARQL queries.

**Comment by justgo129** [comment]
Given that this has been tackled through other tickets, I'm closing #5 as it's now redundant.
