### ISSUE TITLE
F1. first name and middle initial

### ISSUE THREAD

**Issue by congruili** [USGCRP/gcis-ontology#57]
Can we create a term which reflects a string containing a person’s first name and middle initial, similar to foaf:firstName and foaf:lastName?  Or, is foaf:givenName, which we have been using in-lieu of gcis:firstName, sufficient?
(Someone’s comment): What about foaf:name or foaf:nick? The original intent of foaf had heritage in social networking context though.

**Comment by bduggan** [comment]
givenName makes sense (and probably we should change
the database field to "given" too) since this is the term
used by crossref, which is a source of much of the data.

**Comment by zednis** [comment]
:+1: for using `foaf:givenName` in general.

I believe the original question resolves around whether there is an appropriate property for a first name + middle initial (e.g. "Stephan T.").  I believe `foaf:givenName` is valid for this use case.

**Comment by justgo129** [comment]
Fine here.  Also, the question resolves around use of the first initial and middle name (e.g. "John Doe" has an official name of "A. John Doe."  We have several examples of this in GCIS.

**Comment by justgo129** [comment]
To clarify my comment, is foaf:givenName used correctly at:
http://data.globalchange.gov/person/903.thtml

If so, then I'd say let's close this issue since it won't involve changes.

**Comment by zednis** [comment]
@justgo129 I think so.   givenName was defined so that it would not be as restrictive as firstName and could handle 'describing parts of people's names'.  I think our current usage of the property is consistent with it's intent and we can close this issue without making any changes.

**Comment by justgo129** [comment]
Great.  I will close #57 and denote it as such on the list of proposed changes.  Result of issue: no change in template necessary,
