### ISSUE TITLE
G1. organization types

### ISSUE THREAD

**Issue by congruili** [USGCRP/gcis-ontology#59]
We have been using org:Purpose to define an organization as “federal,” “international,” “state,” “commercial,” “private,” “city,” etc.  Per the page at http://www.w3.org/TR/vocab-org/  this may not be an accurate use of org:Purpose.  We are unable to locate a necessary term in the ontologies at: http://oegov.org/ because GCIS includes many organizations which are not part of the Federal government.  Additionally, not all of the organization types in GCIS are listed at: http://en.wikipedia.org/wiki/Category:Types_of_organization .  So, please advise whether we all right using: http://dbpedia.org/property/organizationType ?  Otherwise, please locate an alternate term or create a new one, relating to other terms as necessary.

**Comment by zednis** [comment]
This reminds me of a similar issue with instruments.  We could define a class hierarchy of Organization subclasses but that would be difficult to maintain for the same reason such a hierarchy of instrument types would be hard to maintain.

I think `dbprop:organizationType` with a literal value is a workable solution.  As a bonus, it also follows the same pattern we have been discussing with the proposed `gcis:instrumentType`.

```
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dbpprop:    <http://dbpedia.org/property/> .
dbpprop:organizationType    rdf:type    rdf:Property .
@prefix owl:    <http://www.w3.org/2002/07/owl#> .
dbpprop:organizationType    owl:sameAs  dbpprop:organizationType .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
dbpprop:organizationType    rdfs:label  "organization type"@en .
```

**Comment by bduggan** [comment]
Sounds fine.

**Comment by justgo129** [comment]
+1

**Comment by justgo129** [comment]
@zednis please merge.

**Comment by justgo129** [comment]
Merged (closed) via https://github.com/USGCRP/gcis/pull/198 .
