### ISSUE TITLE
H1. Create a property for “region”

### ISSUE THREAD

**Issue by congruili** [USGCRP/gcis-ontology#60]
Create a term for “region” as used in the NCA3 (see http://nca2014.globalchange.gov/system/files_force/downloads/low/NCA3_Full_Report_Intro_to_Regions_LowRes.pdf?download=1).  Also need a term relating various publications to a region, e.g. in http://data.globalchange.gov/region/hawaii-pacific-us 
Should this new term be similar to: http://data.globalchange.gov/gcis.owl#isDescribedIn but have domain:Region or Report other than domain:Scenario?

**Comment by congruili** [comment]
Is the second part of the question the same as H3?
https://github.com/USGCRP/gcis-ontology/issues/62

**Comment by justgo129** [comment]
Very similar but not identical.  Here (issue #60), the region is the subject and the publication type would be the object.  e.g.: http://data.globalchange.gov/region/hawaii-pacific-us.thtml

**Comment by congruili** [comment]
you mean that we are trying to define a inverse property of H3 (https://github.com/USGCRP/gcis-ontology/issues/62)?

**Comment by justgo129** [comment]
Yep.  My comment about the first portion of the requests remains identical to #62.  I'm all right keeping dbpedia:Region if it is being used correctly at the present time.

**Comment by zednis** [comment]
If I am interpreting the question correctly, you are asking for an inverse property to `dct:spatial` (or whatever we end up using to associate a publication with a region).

If that is correct, my question is do we need an inverse property?

**Comment by justgo129** [comment]
continued in #62

**Comment by justgo129** [comment]
Closing #60 via https://github.com/USGCRP/gcis-ontology/issues/61 and https://github.com/USGCRP/gcis-ontology/pull/88.
