### ISSUE TITLE
H2. Inform whether a region should be a subclass of prov:Entity.

### ISSUE THREAD

**Issue by congruili** [USGCRP/gcis-ontology#61]

**Comment by zednis** [comment]
Is there a use case or scenario where we would want to treat a region as a subclass of `prov:Entity`?  Without such a use case I would say that we should not create the subclass relationship.  Even without the subclass relationship we could still mutli-type instances of region to also have type `prov:Entity`, so unless there is a fundamental reason in our ontology for all regions to be prov entities then I would say we have no requirement for the subclass axiom.

**Comment by justgo129** [comment]
I'm fine as is then, @zednis .  The rationale is that if we decide to create a term gcis:Region, could we relate it to preexisting terms for searchability and robustness?  Right now, we use "a dbpedia:Region."  In the event we decide to use a different term, the question of relating a newly created term to a pre-existing one applies.  Basically, this item is meant as more of a Point of Information than an action item at this time.

**Comment by zednis** [comment]
@justgo129 when you say 'term' are you referring to a class, property, or other?  I have seen the term 'term' colloquially used to mean a class, property, and controlled vocabulary term (think SKOS concept) and I find the current usage very confusing.

**Comment by justgo129** [comment]
Sure.  By term in this instance, I mean a subject, predicate, or object.  So here, if we decide to use a new class to define a Region, e.g. a gcis:Region, a gcis:NCA3region, etc.

**Comment by zednis** [comment]
Yes, I am asking for us to stop using term to mean 'anything in RDF'

**Comment by justgo129** [comment]
I believe we have a consensus to continue using "a dbpedia:Region" then.  @zednis, please confirm that this is an acceptable use given:

https://github.com/USGCRP/gcis/blob/master/lib/Tuba/files/templates/region/object.ttl.tut

and e.g.
https://data.globalchange.gov/region/midwest-us
https://data.globalchange.gov/region/oceans

(or data.globalchange.gov/region ...).

If dbpedia:Region is an acceptable object for how we are using "region," please confirm and close.

**Comment by zednis** [comment]
@justgo129 Looking at the dbpedia RDF I do not see a class dbpedia:Region.

I think we should define our own class Region and give it a definition that meets the needs of GCIS.

first pass of a definition - 'a spatial defined by a common characteristic (e.g. coastal, southwest, rural communities, etc.)'

**Comment by justgo129** [comment]
my bad, I mistook dbpedia:region for it.  
+1 for a slightly modified version of your proposal:
"a spatial area defined by a common characteristic (e.g. coastal...)
"Spatial area" reads awkwardly but I can't immediately think of anything else that could encapture both a contiguous zone and discontinuous ones like various oceans (e.g. "ocean," not "Atlantic Ocean").

**Comment by zednis** [comment]
It seems like our region is synonymous with this definition of zone from New Oxford American Dictionary.

zone |zōn|
noun
1 [ usu. with modifier ] an area or stretch of land having a particular characteristic, purpose, or use, or subject to particular restrictions: a pedestrian zone | the government has declared the city a disaster zone | a no-smoking zone.
• Geography a well-defined region extending around the earth between definite limits, especially between two parallels of latitude: a zone of easterly winds. See also frigid zone, temperate zone, torrid zone.

**Comment by justgo129** [comment]
Cool observation.  There is a dbpedia:Zone but it may be too specific for our purposes given the myriad of examples called out, with some examples of functional regions which won't fit what we're trying to accomplish:

http://dbpedia.org/page/Zone#Geography

Too bad there isn't a dbpedia:FoundationalRegion or we'd be set.

**Comment by justgo129** [comment]
Perhaps something here?
https://bioportal.bioontology.org/ontologies/OGR

While maybe not intended for our purpose, there may be something there.

**Comment by justgo129** [comment]
Let's go with gcis:Region = 
a spatial defined by a common characteristic (e.g. coastal, southwest, rural communities, etc.)
per the suggestion of @zednis.

**Comment by rewolfe** [comment]
Change "spatial" to "spatial area" and it looks good.

**Comment by justgo129** [comment]
Merged at: https://github.com/USGCRP/gcis-ontology/pull/88
Closing #61.
