### ISSUE TITLE
Additional relationship between finding and figure

### ISSUE THREAD

**Issue by CurtTilmes** [USGCRP/gcis-ontology#67]
I see a strong relationship from Chapter -> Figure and Chapter -> Finding,
but do you have a relationship from Finding -> Figure?

something like
http://data.globalchange.gov/report/nca3/chapter/our-changing-climate/finding/us-temperature-increased
gcis:isDepictedIn   (or illustrated by, Supported by, etc.)
http://data.globalchange.gov/report/nca3/chapter/our-changing-climate/figure/observed-us-temperature-change

Everything seems based around the Chapter, but I think of those really as just containers --- the important bits of the report are really the findings.

With that relationship, you could even pop figure thumbnails (the right ones) up into the finding html (and on the finding thumbs page:
http://data.globalchange.gov/report/nca3/finding?thumbs=1)

You could also infer a bit more about the dataset support for findings.  If a dataset was used to make a map or graph supporting a figure that illustrates a finding, then you know that the dataset can be used to understand that finding.

**Comment by bduggan** [comment]
I would like to see these relationships in GCIS, too.

I can add selections to the interface so that someone can
enter them.

What is a good list of relationships to present?  Do we need
a new element in the GCIS ontology?  Do any other ontologies
have something like "gcis:isDepectedIn/SupportedBy" already?

Brian

**Comment by justgo129** [comment]
We have gcis:isSupportedBy but it doesn't explicitly pertain to figures or datasets:
gcis:isSupportedBy  a owl:ObjectProperty ;
    rdfs:label "Is Supported By" ;
    rdfs:comment "A finding is supported by data, models, model runs, software, etc.";
    rdfs:domain gcis:Finding .

**Comment by xgmachina** [comment]
I will update the rdfs:comment of `gcis:isSupportedBy` to reflect the discussion.

**Comment by xgmachina** [comment]
Changed the rdfs:comment to "A finding is supported by or depicted in data, figures,
models, model runs, software, etc.";

**Comment by justgo129** [comment]
Thanks, @xgmachina but given previous discussions, I thought we were getting away from using "model run."

**Comment by justgo129** [comment]
Hi @xgmachina, it would be help me a lot if we could wait to close issues until after the merging of the corresponding pull request.  Thanks so very much.

**Comment by xgmachina** [comment]
Yes, let's leave this open because a few more edits will be made.

**Comment by justgo129** [comment]
@xgmachina, given that #150 has been merged, are we all right to close this ticket?

**Comment by justgo129** [comment]
Closed #67, feel to reopen if desired.
