### ISSUE TITLE
I2. “description_attribution” for platforms and instruments

### ISSUE THREAD

**Issue by congruili** [USGCRP/gcis-ontology#68]
Please create a term for “description_attribution” for platforms and instruments (e.g. for http://data.globalchange.gov/platform/topex-poseidon  it’s “https://eoportal.org/web/eoportal/satellite-mhttps://data.globalchange.gov/lexicon/echoissions/t/topex-poseidon” (without the quotation marks).

**Comment by zednis** [comment]
I am not sure what this request is asking for.

@justgo129 could you please reword or provide another example?

**Comment by justgo129** [comment]
Sure.  
Regarding: http://data.globalchange.gov/platform/topex-poseidon
there is a hyperlink to "directory.eoportal.org...."  That's actually called the description_attribution field in the database.  The description of the entity is pulled directly from directory.eoportal.org...
I am suggesting we find a predicate to express the relationship between a platform/instrument/etc and the URL provided as a "description_attribution."

**Comment by zednis** [comment]
seeAlso?

**Comment by justgo129** [comment]
Hmm, what we need to describe is the URL for the source from which the description described above was pulled.

**Comment by zednis** [comment]
I believe rdfs:seeAlso is appropriate for that need.

```
<https://data.globalchange.gov/lexicon/echoissions/t/topex-poseidon>
   rdfs:seeAlso <https://eoportal.org/web/eoportal/satellite-m> .
```

**Comment by zednis** [comment]
We could also use dublin core terms source http://dublincore.org/documents/dcmi-terms/#terms-source

**Comment by justgo129** [comment]
I like the terms-source.  As a point of information, would one explicitly call out xsd:anyURI or xsd:string given the comment for that term?  Regardless, let's run with it and prepare the pull request.

**Comment by zednis** [comment]
Neither, it is intended to be used with non-literal values (i.e. as an object property)
see http://wiki.dublincore.org/index.php/User_Guide/Publishing_Metadata#dcterms:source.

If we want to reference a URL we would do this:

```
<https://data.globalchange.gov/lexicon/echoissions/t/topex-poseidon>
   dcterms:source <https://eoportal.org/web/eoportal/satellite-m> .
```

If we don't have a URL, just a string description of the source, we would do this:

```
<https://data.globalchange.gov/lexicon/echoissions/t/topex-poseidon>
   dcterms:source [ rdfs:label "description of source" ] .
```

**Comment by justgo129** [comment]
Great.  Let's run with it and merge.
