### ISSUE TITLE
I5. relating a lexicon to instruments and missions

### ISSUE THREAD

**Issue by congruili** [USGCRP/gcis-ontology#69]
Please create a term relating a lexicon to instruments and missions (http://data.globalchange.gov/lexicon/ceos)

**Comment by zednis** [comment]
Unless I am misunderstanding the purpose of a lexicon, a lexicon is just a controlled vocabulary.  I do not think there should be specific property for association a lexicon to instrument or mission individuals.

**Comment by justgo129** [comment]
@zednis your logic makes sense.  If @bduggan and @rewolfe agree, we can close this ticket.

**Comment by bduggan** [comment]
I would say we have covered lexicons more generally already; this ticket can be
closed.

**Comment by zednis** [comment]
If @rewolfe agrees I will close this ticket.

**Comment by rewolfe** [comment]
Yes, let's close this ticket.

On Fri, Jul 24, 2015 at 11:03 AM, Stephan Zednik notifications@github.com
wrote:

> If @rewolfe https://github.com/rewolfe agrees I will close this ticket.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/69#issuecomment-124552204
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
Closed #69 without making a change in github.
