### ISSUE TITLE
domain of hasGoverningOrganization is intersection of gcis:Project and gcis:Instrument

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#71]
The current domain of `gcis:hasGoverningOrganization` is both `gcis:Project` and `gcis:Instrument`.  I believe this would be interpreted as an intersection instead of a union.

```
gcis:hasGoverningOrganization a owl:ObjectProperty ;
    rdfs:label "Has Governing Organization" ;
    rdfs:comment "An organization is responsible for a project." ;
    rdfs:domain gcis:Project, gcis:Instrument ;
    rdfs:range gcis:Organization .
```

I believe the intended domain as a union should be:

```
gcis:hasGoverningOrganization a owl:ObjectProperty ;
    rdfs:label "Has Governing Organization" ;
    rdfs:comment "An organization is responsible for a project." ;
    rdfs:domain [ a owl:Class ;
                owl:unionOf( gcis:Project gcis:Instrument ) ;
        ] ;
    rdfs:range gcis:Organization .
```

**Comment by rewolfe** [comment]
It seems like we need to modify the definition to make it broader (not just
a project). Also, the domain could be broaden to include other classes,
e.g. Platform.

**Comment by zednis** [comment]
Perhaps we use a very broad domain such as `prov:Entity` or remove the domain altogether?

**Comment by rewolfe** [comment]
I'm okay with removing the domain altogether for now.

We are thinking about adding the concept of Project in support of ideas
that USGS has for the ESIP testbed.  At that point, we may want to think
about how instruments and platforms are related to projects.  What NASA
calls missions could be considered a special type (subclass) of project.
Also, what we have been thinking about as earth observing systems could
also be considered a special type of project.

On Fri, Jul 24, 2015 at 1:13 AM, Stephan Zednik notifications@github.com
wrote:

> Perhaps we use a very broad domain such as prov:Entity or remove the
> domain altogether?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/71#issuecomment-124334368
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
+1 for removing the domain

**Comment by justgo129** [comment]
Domain for gcis:hasGoverningOrganization removed.
