### ISSUE TITLE
E1 Mapping GCIS 'spatial' properties to properties in other ontologies and schemas

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#73]
For images and figures, can gcis:northBoundLatitude, etc. be related to fao:hasMaxLatitude, etc.?  (see http://www.fao.org/countryprofiles/geoinfo/geopolitical/resource/United_States_of_America)  Maybe this could be related to the geo ontology?  Is there something in SWEET to which we can also link?
Someone’s comment: See reuse of gmd. e.g. gmd:northBoundLatitude

**Comment by justgo129** [comment]
Given the lack of action on this and our ongoing discussion with ISO, I am closing #73 for the time-being.  I'd be happy to reopen this at a later date.
