### ISSUE TITLE
E2 Properties 'cites' and 'isCitedBy' in GCIS ontology

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#74]
Relate http://data.globalchange.gov/gcis.owl#cites to http://vocab.ox.ac.uk/cito#term_cites (cito:cites).  Also, for consistency, create a term similar to http://vocab.ox.ac.uk/cito#term_isCitedBy within the GCIS ontology as there is no entry for gcis:isCitedBy but there is for gcis:cites.

**Comment by justgo129** [comment]
Seeing the lack of action on this combined with this being a relatively low priority item, coupled with the fact that gcis:cites isn't used in any of the turtle templates, I advise removing gcis:cites from the owl file and closing this ticket.  @xgmachina and @zednis are you fine with this approach?

**Comment by justgo129** [comment]
gcis:cites has been removed from the owl file.  Closed https://github.com/USGCRP/gcis-ontology/issues/74.
