### ISSUE TITLE
E3 gcis:contactPoint and gcis:PointofContact

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#75]
Relate http://data.globalchange.gov/gcis.owl#contactPoint to prov:Role.
     As an aside, the ontology contains gcis:ContactPoint (specific to datasets) and gcis:PointOfContact (more generally).  Please inform whether we need both.

**Comment by xgmachina** [comment]
`gcis:contactPoint` is an object property, and `gcis:PointOfContact` is a `prov:Role`. They each has a different function in the GCIS ontology.

**Comment by xgmachina** [comment]
I would suggest to revise all the instances of `prov:Role` in the GCIS ontology --> To make the first letter in lower case. For example, `gcis:PointOfContact` to `gcis:pointOfContact`

**Comment by zednis** [comment]
:+1: to @xgmachina's proposal to start the instance role with a lowercase.  We could go even further and make the the URI `gcis:point_of_contact` to differentiate it from the conventions used with class and property URIs.

**Comment by justgo129** [comment]
+1

**Comment by justgo129** [comment]
@zednis or @xgmachina please feel free to take action accordingly.

**Comment by zednis** [comment]
I have updated the qnames for role instances, but we have not yet decided on a resolution to the original request to relate `gcis:contactPoint` to `gcis:point_of_contact`.

**Comment by justgo129** [comment]
@zednis good point.  What is your opinion on this matter?  I am also all right with resolving the particular question as "no action taken."  My instinct is to remove gcis:contactPoint although I am open to other options.

**Comment by justgo129** [comment]
My gut is to remove gcis:contactPoint.  @xgmachina or @zednis , is the portion of the turtle written at: https://data.globalchange.gov/role_type/point_of_contact.thtml correct given the aforementioned changes?

**Comment by zednis** [comment]
@justgo129 the RDF at the link you posted looks fine to me.

In going back to the OP of the ticket, I am fine with having both a point_of_contact provenance role and a `gcis:contactPoint` property.

1) The provenance role is intended specifically to state _'the function of an entity or agent with respect to an activity, in the context of a usage, generation, invalidation, association, start, and end.'_
2) We will want to generally be able to assert that some agent is the contact point for some thing without putting that agent in the context of their relationship to some activity.

As such I recommend we keep `gcis:contactPoint` and that we evaluate any current uses of the point_of_contact instance to make sure it is in line with the definition for provenance roles mentioned above.

**Comment by justgo129** [comment]
@zednis this seems fine to me.  A search for "point_of_contact" (w/o the quotation marks) in the gcis github repo didn't turn up any instances of this role.

**Comment by zednis** [comment]
thanks @justgo129.

I recommend closing this issue with no changes to ``gcis:contactPoint`.

**Comment by justgo129** [comment]
Done.  Closed #75 with no action taken.
