### ISSUE TITLE
E4 Create something like 'gcis:producedDataset' for images

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#76]
Create something like http://data.globalchange.gov/gcis.owl#producedDataset for images.

**Comment by xgmachina** [comment]
We can easily add a new property `gcis:producedImage`, but I would like to extend the discussion a bit more:

The current GCIS ontology has a property `gcis:wasCreatedBy`. Its domain is `gcis:Image` and range is `gcis:ImageCreation`. To see more details the ontology document might be easier to follow: http://data.globalchange.gov/gcis.owl#d4e1002

Similarly, for datasets there is a property `gcis:wasCapturedBy`. Its domain is `gcis:Dataset` and range is `gcis:DatasetCapture`. More details: http://data.globalchange.gov/gcis.owl#d4e972

The range of `gcis:producedDataset` is `gcis:Datset` but the domain is null. My thought here is, can we make `gcis:wasCapturedBy` and `gcis:producedDataset` inverse properties? Do we need to make some updates to the property name as well as their domain and range?

**Comment by justgo129** [comment]
fyi all - gcis:producedDataset is defined at:
http://data.globalchange.gov/gcis.owl#d4e809

Thanks for the heads-up, Marshall.  Is it all right with everyone to have gcis:wasCreatedBy associated with Images and gcis:wasCapturedBy with Dataset?  While it works semantically, it might be clearer to include "image" or "dataset" in the property names to avoid confusion.  I'll defer to everyone else though.

**Comment by justgo129** [comment]
Leaving as is with no change.

**Comment by justgo129** [comment]
Closing #76.

**Comment by justgo129** [comment]
Reopened #76 in case recent changes in the ontology file have changed the manner in which we address this ticket.  @zednis and @xgmachina I'm curious as to your thoughts about my comments above.

**Comment by zednis** [comment]
Reviewing this discussion for the first time in a while, lots of comments
- `gcis:producedDataset` is a subproperty of `prov:generated`.  It doesn't really add anything to `prov:generated` beyond having a narrower domain and a different label.
- presumably `gcis:producedImage` would be the same.
- I do not think either`gcis:producedDataset` or `gcis:producedImage` are needed - we can just use `prov:generated`
- `gcis:wasCreatedBy` is a subproperty of `prov:wasGeneratedBy` with image-specific domain and range.  I think the domain and range for this property are unnecessarily narrow based on its name and label
- I do not think `gcis:wasCreatedBy` is needed - we can just use `prov:wasGeneratedBy`

**Comment by justgo129** [comment]
:+1: for removing uncecessary terms.

**Comment by justgo129** [comment]
@zednis when you return from PTO, please feel free to act on your comment above ("reviewing this discussion for...") and create the pull request.

**Comment by justgo129** [comment]
Closed #76 due to merged #160.
