### ISSUE TITLE
E7 Differentiate between 'gcis:isFindingOf' and 'gcis:isBasedOn'

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#78]
Clarify differentiate between gcis:isFindingOf and gcis:isBasedOn since a publication is considered a chapter.  An example of how we have been using gcis:isFindingOf is available at https://data.globalchange.gov/report/nca3/chapter/our-changing-climate/finding/extreme-precipitation-increase.thtml

**Comment by xgmachina** [comment]
In the original desgin of GCIS ontology, `gcis:isBasedOn` is used to describe that a (report) finding was derived from one or more (chapter) findings.
Details: http://data.globalchange.gov/gcis.owl#d4e618

The domain of `gcis:isFindingOf` is open.

**Comment by justgo129** [comment]
Interesting.  @aulenbac what do you think?

**Comment by justgo129** [comment]
Thanks for the clarification, @xgmachina.  Although the difference now makes more sense, could we change the predicates to clarify the distinction?  @rewolfe ?

**Comment by justgo129** [comment]
Let's remove gcis:isBasedOn then.

**Comment by justgo129** [comment]
closed #78 due to merged #140.
