### ISSUE TITLE
C2. represent duration of activities

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis-ontology#8]
Create something synonymous to dcterms:SizeOrDuration since that term requires a specific time format.  To describe the time requirement of an activity, we have been using strings, e.g. “6 hours”  (http://data.globalchange.gov/activity/0158fa86-nca3-ghcn-daily-r201305-process).  A relationship with Dublin Core would still be good though if it can be salvaged.

example from http://data.globalchange.gov/activity/0158fa86-nca3-ghcn-daily-r201305-process.ttl

```
## Duration of the activity
   dcterms:SizeOrDuration "6 hours"^^xsd:string;
```

**Comment by zednis** [comment]
First off, this usage of dctersm:SizeOrDuration is incorrect.  SizeOrDuration is a class, not a property.  In dublin core the proper term to use is dcterms:extent.  The range of dcterms:extent is  dcterms:SizeOrDuration.  

Here is a link with an example of using dcterms:extent.

http://wiki.dublincore.org/index.php/User_Guide/Publishing_Metadata#dcterms:extent

This is what the example from above would look like with the correct modeling.

```
<http://data.globalchange.gov/activity/0158fa86-nca3-ghcn-daily-r201305-process>
  a prov:Activity ;
  dcterms:extent [ rdf:value "6 hours"^^xsd:string; ] .
```

**Comment by zednis** [comment]
Also, I do not know what you mean by 'Create something synonymous to dcterms:SizeOrDuration since that term requires a specific time format' - the value of a dcterms:SizeOrDuration resource does not require a specific time format.

**Comment by bduggan** [comment]
These are stored as a postgres interval data, so the values in the turtle can be rendered in any format.

**Comment by zednis** [comment]
Right, I just did not understand where the assumption that the 'term' dcterms:SizeOrDuration required a specific time format came from.  It doesn't.
