### ISSUE TITLE
Journals

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis-ontology#80]
Inspired by https://github.com/USGCRP/gcis/pull/191,  I am wondering whether we could relate dbpedia:AcademicJournal (http://dbpedia.org/page/Academic_journal) to gcis:Journal, or rewrite the end of the code for journals to:

"a gcis:Journal, dbpedia:AcademicJournal."

Looking at dbpedia, I see many publication types which relate, at least at first glance, to those in gcis.

**Comment by zednis** [comment]
`dbpedia:AcademicJournal` is an instance, not a class.  It is an RDF description of the wikipedia page http://en.wikipedia.org/wiki/Academic_journal.

My gut reaction is that we do not need to tie our class to this instance and we definitely should not attempt to use it as a class.

**Comment by justgo129** [comment]
Great.  Closed #80.
