### ISSUE TITLE
E10 Property for the 'statement' text of a finding

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#83]
To describe the text of a finding, dcterms:description is being used, e.g. http://data.globalchange.gov/report/nca3/chapter/water-resources/finding/summer-droughts-intensify.thtml
This is called a “statement” in gcis.

Is dcterms:description being used correctly?  If not, please locate a term from another ontology, and/or create a term like “FindingStatement” in the gcis ontology and relate it to other terms accordingly. 
 .
See http://data.globalchange.gov/gcis.owl#Finding (note that other parts of the finding, e.g. uncertainty characterization, are included in the gcis ontology, so it’s only fitting that the “statement” part gets a term)..

**Comment by xgmachina** [comment]
In my understanding `dct:description` works well there. We can also create `gcis:statement` to make it more specific in the context of GCIS.

**Comment by justgo129** [comment]
For consistency purposes, I'd like to create something akin to "gcis:statement," relating it to dcterms:description.  Otherwise dcterms:description is fine.

**Comment by justgo129** [comment]
I propose the following.

New term: gcis:findingStatement
hasdomain: gcis:Finding
range: dcterms:description
Definition: "The text of a Finding in a Highly Influential Scientific Document"

Please ensure that my domain and range are accurate and proceed with this.

**Comment by justgo129** [comment]
Actually, I just remembered that I could take the domain and range from the other properties associated with components of findings.  I just did that in the pull request I initiated above.  Upon the merging of that request, we can close this ticket.
