### ISSUE TITLE
A1 Literal defintions of terms in GCIS ontology

### ISSUE THREAD

**Issue by xgmachina** [USGCRP/gcis-ontology#84]
Examine the definitions of terms in the gcis ontology and correct those which are unclear or which use the term to be defined in the actual definition.  Here are some examples:

Figure Compiling : An activity that compiles figures.
Finding : A significant point or central theme of an investigation.
Image Creation : An activity that creates images.
At Location : Something is at a geographic or non-geographic place.
Publication Preparation : An activity that prepares publications.
hasTemporalUnit:A temporal resolution has one or more temporal units

**Comment by xgmachina** [comment]
There could be more such literal definitions that need update. Let's extend the list here.

**Comment by justgo129** [comment]
ChapterWriting: An activity that writes chapters.
ConfidenceAssertion: The confidence assertion of a traceable account.
Dataset Capture: An activity that captures datasets.
SoftwareAgent: A software agent is a running software system. 
TableCompiling: An activity that compiles tables.
descriptionOfEvidenceBase: A finding has a description of evidence base.
EndDate: The end date of a temporalExtent
extentTypeCode: The extent type code of a spatial extent.
hasURL: A resource has a URL
publicationStatus: The status of the publication of a document.

**Comment by justgo129** [comment]
Note: very few of these are employed in the existing turtle templates anyway.

**Comment by justgo129** [comment]
@rewolfe - currently the only instances of these used in the turtle templates are:
gcis:hasURL
gcis:descriptionOfEvidenceBase
gcis:Finding (but that definition is reading all right to me now).

However, we definitely need to change the definitions for the following in order to be more insightful.  It might just be best to find out the official definitions from various USGCRP assessments and use those.  What do you think?

gcis:findingProcess a owl:DatatypeProperty ;
    rdfs:label "Finding Process" ;
    rdfs:comment "A finding has a description of the finding generation process." ;
    rdfs:domain gcis:Finding ;
    rdfs:range xsd:string .

gcis:descriptionOfEvidenceBase a owl:DatatypeProperty ;
    rdfs:label "Description of Evidence Base" ;
    rdfs:comment "A finding has a description of evidence base." ;
    rdfs:domain gcis:Finding ;
    rdfs:range xsd:string .

gcis:newInformationAndRemainingUncertainties a owl:DatatypeProperty ;
    rdfs:label "New Information and Remaining Uncertainties" ;
    rdfs:comment "A finding has a description of new information and remaining uncertainties." ;
    rdfs:domain gcis:Finding ;
    rdfs:range xsd:string .

gcis:assessmentOfConfidenceBasedOnEvidence a owl:DatatypeProperty ;
    rdfs:label "Assessment of Confidence Based on Evidence" ;
    rdfs:comment "A finding has an assessment of confidence based on evidence." ;
    rdfs:domain gcis:Finding ;
    rdfs:range xsd:string .

**Comment by justgo129** [comment]
Indeed, the defns of these four are in the "About this Report" chapter.  I'll update the four accordingly, plus that for gcis:hasURL.  We can then finish off this ticket.

**Comment by xgmachina** [comment]
Revisit definition of gcis:Dataset to encompass health data in addition to those from the NCA3.

**Comment by justgo129** [comment]
Merged #99 (pull request).

**Comment by justgo129** [comment]
Closed #84.  A little later on, I'd like to revisit the definitions one last time, remove unused classes, properties, etc. from the owl file but for now I'll close this ticket.  I'll spin off the health dataset aspect.
