### ISSUE TITLE
dbpedia:Natural_number (class as property)

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis-ontology#95]
As a "child" issue of: https://github.com/USGCRP/gcis-ontology/issues/12 , we use dbpedia:Natural_number as a property.

https://github.com/USGCRP/gcis/blob/master/lib/Tuba/files/templates/finding/object.ttl.tut

The aim was to identify a predicate to refer to a number to the right of a decimal place.  e.g. the "11" in "Finding 2.11."

I'm not even sure we need this triple and can't immediately think of applicable use cases.  If we decide to keep it, we'll need a new predicate.

**Comment by zednis** [comment]
I do not think we need to have an additional separate statement for the number to the right of the decimal point in the number value of the finding number.

**Comment by justgo129** [comment]
Sounds reasonable to me.  I'll prepare the pull request to have it removed.  We could always revert it later upon request.

**Comment by zednis** [comment]
:+1:

**Comment by justgo129** [comment]
Closed #95 on behalf of https://github.com/USGCRP/gcis/pull/209.
